# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TurnLeftBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TurnLeftBtn.setGeometry(QtCore.QRect(30, 60, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TurnLeftBtn.setFont(font)
        self.TurnLeftBtn.setAutoFillBackground(False)
        self.TurnLeftBtn.setDefault(True)
        self.TurnLeftBtn.setFlat(False)
        self.TurnLeftBtn.setObjectName("TurnLeftBtn")
        self.TurnRightBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TurnRightBtn.setGeometry(QtCore.QRect(360, 60, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TurnRightBtn.setFont(font)
        self.TurnRightBtn.setDefault(True)
        self.TurnRightBtn.setFlat(False)
        self.TurnRightBtn.setObjectName("TurnRightBtn")
        self.ResetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ResetBtn.setGeometry(QtCore.QRect(200, 240, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ResetBtn.setFont(font)
        self.ResetBtn.setDefault(True)
        self.ResetBtn.setFlat(False)
        self.ResetBtn.setObjectName("ResetBtn")
        self.notifyLbl = QtWidgets.QLabel(self.centralwidget)
        self.notifyLbl.setEnabled(True)
        self.notifyLbl.setGeometry(QtCore.QRect(20, 10, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(False)
        self.notifyLbl.setFont(font)
        self.notifyLbl.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 0, 0);")
        self.notifyLbl.setObjectName("notifyLbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TurnLeftBtn.setText(_translate("MainWindow", "Turn Left"))
        self.TurnRightBtn.setText(_translate("MainWindow", "Turn Right"))
        self.ResetBtn.setText(_translate("MainWindow", "Reset"))
        self.notifyLbl.setText(_translate("MainWindow", "Label"))
