# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lastWindow(object):
    def setupUi(self, lastWindow):
        lastWindow.setObjectName("lastWindow")
        lastWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(lastWindow.sizePolicy().hasHeightForWidth())
        lastWindow.setSizePolicy(sizePolicy)
        lastWindow.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.centralwidget = QtWidgets.QWidget(lastWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 30, 551, 251))
        self.frame.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 50, 421, 131))
        self.label.setObjectName("label")
        self.mainMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mainMenuBtn.setGeometry(QtCore.QRect(210, 350, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.mainMenuBtn.setFont(font)
        self.mainMenuBtn.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.mainMenuBtn.setObjectName("mainMenuBtn")
        lastWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(lastWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        lastWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(lastWindow)
        self.statusbar.setObjectName("statusbar")
        lastWindow.setStatusBar(self.statusbar)

        self.retranslateUi(lastWindow)
        QtCore.QMetaObject.connectSlotsByName(lastWindow)

    def retranslateUi(self, lastWindow):
        _translate = QtCore.QCoreApplication.translate
        lastWindow.setWindowTitle(_translate("lastWindow", "Match Finished"))
        self.label.setText(_translate("lastWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Match finished</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">press to go to main menu</span></p></body></html>"))
        self.mainMenuBtn.setText(_translate("lastWindow", "Main Menu"))
