# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matchInstructionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_matchInstructionsWindow(object):
    def setupUi(self, matchInstructionsWindow):
        matchInstructionsWindow.setObjectName("matchInstructionsWindow")
        matchInstructionsWindow.resize(700, 559)
        matchInstructionsWindow.setStyleSheet("background-color: rgb(129, 129, 129);")
        self.centralwidget = QtWidgets.QWidget(matchInstructionsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 681, 291))
        self.frame.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 10, 471, 71))
        self.label.setObjectName("label")
        self.matchDescriptionLabel = QtWidgets.QLabel(self.frame)
        self.matchDescriptionLabel.setGeometry(QtCore.QRect(30, 80, 641, 151))
        self.matchDescriptionLabel.setTextFormat(QtCore.Qt.RichText)
        self.matchDescriptionLabel.setScaledContents(False)
        self.matchDescriptionLabel.setWordWrap(False)
        self.matchDescriptionLabel.setObjectName("matchDescriptionLabel")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(450, 420, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.startBtn.setFont(font)
        self.startBtn.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.startBtn.setObjectName("startBtn")
        self.mainMenuBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mainMenuBtn.setGeometry(QtCore.QRect(30, 420, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.mainMenuBtn.setFont(font)
        self.mainMenuBtn.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.mainMenuBtn.setObjectName("mainMenuBtn")
        matchInstructionsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(matchInstructionsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        matchInstructionsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(matchInstructionsWindow)
        self.statusbar.setObjectName("statusbar")
        matchInstructionsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(matchInstructionsWindow)
        QtCore.QMetaObject.connectSlotsByName(matchInstructionsWindow)

    def retranslateUi(self, matchInstructionsWindow):
        _translate = QtCore.QCoreApplication.translate
        matchInstructionsWindow.setWindowTitle(_translate("matchInstructionsWindow", "Match Instructions"))
        self.label.setText(_translate("matchInstructionsWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">Match Instructions</span></p></body></html>"))
        self.matchDescriptionLabel.setText(_translate("matchInstructionsWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; font-style:italic;\">All the details about the match will go here aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</span></p></body></html>"))
        self.startBtn.setText(_translate("matchInstructionsWindow", "Start Match"))
        self.mainMenuBtn.setText(_translate("matchInstructionsWindow", "Main Menu"))
