# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seRangeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rangeWindow(object):
    def setupUi(self, rangeWindow):
        rangeWindow.setObjectName("rangeWindow")
        rangeWindow.resize(1024, 600)
        rangeWindow.setMaximumSize(QtCore.QSize(1024, 600))
        
        rangeWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint) # this will hide the title bar
        rangeWindow.setWindowTitle("no title") # set the title
        
        rangeWindow.setStyleSheet("QMainWindow#rangeWindow { background-image: url(:/images/background.jpg); }\n"
"")
        self.centralwidget = QtWidgets.QWidget(rangeWindow)
        self.centralwidget.setStyleSheet("background-color: transparent;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(69, 9, 891, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.setBtn2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn2.setFont(font)
        self.setBtn2.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn2.setObjectName("setBtn2")
        self.gridLayout.addWidget(self.setBtn2, 1, 0, 1, 1)
        self.setBtn3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn3.setFont(font)
        self.setBtn3.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn3.setObjectName("setBtn3")
        self.gridLayout.addWidget(self.setBtn3, 2, 0, 1, 1)
        self.setBtn5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn5.setFont(font)
        self.setBtn5.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn5.setObjectName("setBtn5")
        self.gridLayout.addWidget(self.setBtn5, 6, 0, 1, 1)
        self.setBtn1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setBtn1.setMaximumSize(QtCore.QSize(252, 16777215))
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn1.setFont(font)
        self.setBtn1.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn1.setObjectName("setBtn1")
        self.gridLayout.addWidget(self.setBtn1, 0, 0, 1, 1)
        self.setBtn4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn4.setFont(font)
        self.setBtn4.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn4.setObjectName("setBtn4")
        self.gridLayout.addWidget(self.setBtn4, 3, 0, 1, 1)
        self.setBtn6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.setBtn6.setMaximumSize(QtCore.QSize(252, 16777215))
        font = QtGui.QFont()
        font.setFamily("SerpentineEF")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.setBtn6.setFont(font)
        self.setBtn6.setStyleSheet("background-color: rgb(202, 202, 202);")
        self.setBtn6.setObjectName("setBtn6")
        self.gridLayout.addWidget(self.setBtn6, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(385, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        rangeWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rangeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        rangeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rangeWindow)
        self.statusbar.setObjectName("statusbar")
        rangeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(rangeWindow)
        QtCore.QMetaObject.connectSlotsByName(rangeWindow)

    def retranslateUi(self, rangeWindow):
        _translate = QtCore.QCoreApplication.translate
        rangeWindow.setWindowTitle(_translate("rangeWindow", "Set Range"))
        self.setBtn2.setText(_translate("rangeWindow", "Range 2"))
        self.setBtn3.setText(_translate("rangeWindow", "Range 3"))
        self.setBtn5.setText(_translate("rangeWindow", "Range 5"))
        self.setBtn1.setText(_translate("rangeWindow", "Range 1"))
        self.setBtn4.setText(_translate("rangeWindow", "Range 4"))
        self.setBtn6.setText(_translate("rangeWindow", "Range 6"))
import resources_rc
